const parsePositiveInt = (value, fallback) => {
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
};

const AUTH_IDLE_TIMEOUT_MINUTES = parsePositiveInt(process.env.AUTH_IDLE_TIMEOUT_MINUTES, 30);
const AUTH_ABSOLUTE_TIMEOUT_HOURS = parsePositiveInt(process.env.AUTH_ABSOLUTE_TIMEOUT_HOURS, 8);
const AUTH_ACTIVITY_TOUCH_INTERVAL_MINUTES = parsePositiveInt(
  process.env.AUTH_ACTIVITY_TOUCH_INTERVAL_MINUTES,
  5
);

const AUTH_IDLE_TIMEOUT_MS = AUTH_IDLE_TIMEOUT_MINUTES * 60 * 1000;
const AUTH_ABSOLUTE_TIMEOUT_MS = AUTH_ABSOLUTE_TIMEOUT_HOURS * 60 * 60 * 1000;
const AUTH_ACTIVITY_TOUCH_INTERVAL_MS = AUTH_ACTIVITY_TOUCH_INTERVAL_MINUTES * 60 * 1000;
const AUTH_TOKEN_TTL = `${AUTH_ABSOLUTE_TIMEOUT_HOURS}h`;

module.exports = {
  AUTH_IDLE_TIMEOUT_MINUTES,
  AUTH_ABSOLUTE_TIMEOUT_HOURS,
  AUTH_ACTIVITY_TOUCH_INTERVAL_MINUTES,
  AUTH_IDLE_TIMEOUT_MS,
  AUTH_ABSOLUTE_TIMEOUT_MS,
  AUTH_ACTIVITY_TOUCH_INTERVAL_MS,
  AUTH_TOKEN_TTL,
};
